server:
  port: 8080

spring:
  application:
    name: trustchain-backend

fabric:
  enabled: false # Set true when connecting to active Fabric test-network
  mspId: Org1MSP
  certPath: organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
  keyPath: organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
  tlsCertPath: organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
  peerEndpoint: localhost:7051
  overrideAuth: peer0.org1.example.com
  channelName: mychannel
  chaincodeName: productcontract
